### ISSUE TITLE
S3 bucket usage

### ISSUE THREAD

**Issue by spock** [dynamicbk/ClashBotDiscord#72]
hey dynamicbk, thanks for writing what looks like a decent Python bot.
I'm currently trying to set it up, to give it a try.

In the configs, you specify S3 bucket properties/tokens.
From the code, only `content_creator.py` refers to those.
It looks like you are generating some plots/webpages with stats and saving them to S3.

How do you setup S3 bucket permissions, do you have that described/screenshotted somewhere? ACL, policy, CORS, access points?...

It's also not entirely clear how/if CloudWatch is related....
I guess more code reading for me, hoping the bot in the end will be doing what I think it is doing :)

**Comment by dynamicbk** [comment]
I currently just have public buckets for those images, as none of the data is private, since it all comes from the Clash API anyways.

CloudWatch is currently only used for metrics tracking how the bot is running, such as number of Clash API calls per hour.

**Comment by spock** [comment]
public as in world-writable?...  
sorry, have no prior experience with S3 permissions.  
is the below sufficient after creating the S3 bucket, or do I still need to adjust some ACLs?  

![image](https://user-images.githubusercontent.com/584494/71661934-0869b380-2d50-11ea-8da6-0936b55343ef.png)

I have also added this:  
![image](https://user-images.githubusercontent.com/584494/71661996-436be700-2d50-11ea-97c4-177f1fac43a9.png)

Which resulted in this:  
![image](https://user-images.githubusercontent.com/584494/71662013-52eb3000-2d50-11ea-9634-4cdbf45ccbd9.png)

Looks correct to you?  
How can I test if that works?

**Comment by spock** [comment]
For CloudWatch, is it enough to just set this checkbox when creating the S3 bucket?  
Sorry, I'm really new to these parts of the AWS ecosystem :)  

![image](https://user-images.githubusercontent.com/584494/71662529-18829280-2d52-11ea-92e3-0d94cfc21cc4.png)

**Comment by spock** [comment]
Update: I guess setting that checkbox above did the trick: cloudwatch now reports a few requests, and I'm no longer getting an error after `putting metrics`:
> 2020-01-02 14:20:21:DEBUG:ClashBotDataManager: Emitting metric: 1 for Clan War, Processed, emit_if_zero=True
> 2020-01-02 14:20:21:DEBUG:ClashBotDataManager: putting metrics
> 2020-01-02 14:35:30:DEBUG:ClashBotDataManager: checking processing data
> 2020-01-02 14:35:30:DEBUG:ClashBotDataManager: sleeping for 60s

The S3 bucket itself seems to be empty so far.

**Comment by spock** [comment]
Yep, everything works, although I got charts/html uploaded to S3 even when using the `_local` commands... And html files have server-local paths in them. When invoking the `_s3` commands, image paths are correct and it all works, yay!

You've written an impressively good bot.
