### ISSUE TITLE
is fetched_raw_data important to keep? #support #question

### ISSUE THREAD

**Issue by spock** [dynamicbk/ClashBotDiscord#81]
The bot has been running for a few days now, and the `fetched_raw_data` folder has already grown to about a gigabyte. It appears to contain `.json` files fetched from supercell API; largest files appear to be `clanPlayerAchievements`.

- would it be safe to delete input `.json` as soon as the data is processed and imported into the database? (assuming that the database is somehow backed up...)
- in the event of a bad database file crash, can the bot currently re-use those `.json` files to "playback" older events/updates history?

**Comment by dynamicbk** [comment]
You can absolutely delete it, that data is used only when rebuilding the DB from scratch, which I find value in. If you don’t care about that, delete it all, or you can also delete portions of it. 

I have plans to allow disabling of saving any data locally, as well as saving less data each day.
